
INSERT INTO states(id,name,tel_prefix) VALUES (1,N'آذربایجان شرقی',N'041');
INSERT INTO states(id,name,tel_prefix) VALUES (2,N'آذربایجان غربی',N'044');
INSERT INTO states(id,name,tel_prefix) VALUES (3,N'اردبیل',N'045');
INSERT INTO states(id,name,tel_prefix) VALUES (4,N'اصفهان',N'031');
INSERT INTO states(id,name,tel_prefix) VALUES (5,N'البرز',N'026');
INSERT INTO states(id,name,tel_prefix) VALUES (6,N'ایلام',N'084');
INSERT INTO states(id,name,tel_prefix) VALUES (7,N'بوشهر',N'077');
INSERT INTO states(id,name,tel_prefix) VALUES (8,N'تهران',N'021');
INSERT INTO states(id,name,tel_prefix) VALUES (9,N'چهارمحال و بختیاری',N'038');
INSERT INTO states(id,name,tel_prefix) VALUES (10,N'خراسان جنوبی',N'056');
INSERT INTO states(id,name,tel_prefix) VALUES (11,N'خراسان رضوی',N'051');
INSERT INTO states(id,name,tel_prefix) VALUES (12,N'خراسان شمالی',N'058');
INSERT INTO states(id,name,tel_prefix) VALUES (13,N'خوزستان',N'061');
INSERT INTO states(id,name,tel_prefix) VALUES (14,N'زنجان',N'024');
INSERT INTO states(id,name,tel_prefix) VALUES (15,N'سمنان',N'023');
INSERT INTO states(id,name,tel_prefix) VALUES (16,N'سیستان و بلوچستان',N'054');
INSERT INTO states(id,name,tel_prefix) VALUES (17,N'فارس',N'071');
INSERT INTO states(id,name,tel_prefix) VALUES (18,N'قزوین',N'028');
INSERT INTO states(id,name,tel_prefix) VALUES (19,N'قم',N'025');
INSERT INTO states(id,name,tel_prefix) VALUES (20,N'کردستان',N'087');
INSERT INTO states(id,name,tel_prefix) VALUES (21,N'کرمان',N'034');
INSERT INTO states(id,name,tel_prefix) VALUES (22,N'کرمانشاه',N'083');
INSERT INTO states(id,name,tel_prefix) VALUES (23,N'کهگیلویه و بویراحمد',N'074');
INSERT INTO states(id,name,tel_prefix) VALUES (24,N'گلستان',N'017');
INSERT INTO states(id,name,tel_prefix) VALUES (25,N'لرستان',N'066');
INSERT INTO states(id,name,tel_prefix) VALUES (26,N'گیلان',N'013');
INSERT INTO states(id,name,tel_prefix) VALUES (27,N'مازندران',N'011');
INSERT INTO states(id,name,tel_prefix) VALUES (28,N'مرکزی',N'086');
INSERT INTO states(id,name,tel_prefix) VALUES (29,N'هرمزگان',N'076');
INSERT INTO states(id,name,tel_prefix) VALUES (30,N'همدان',N'081');
INSERT INTO states(id,name,tel_prefix) VALUES (31,N'یزد',N'035');
